cicd-db

diff --git a/.github/workflows/cicd-tienda-db.yml b/.github/workflows/cicd-tienda-db.yml
--- a/.github/workflows/cicd-tienda-db.yml
+++ b/.github/workflows/cicd-tienda-db.yml
@@ -27,16 +27,17 @@ jobs:
       id: login-ecr
       uses: aws-actions/amazon-ecr-login@v2
 
-    - name: Diagnostico de variables
-      run: |
-        echo "Registry detectado: ${{ steps.login-ecr.outputs.registry }}"
-        echo "Esta variable debe contener algo como: 271179226854.dkr.ecr.us-east-1.amazonaws.com"
-
     - name: Build, Tag y Push a ECR
       env:
         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
         IMAGE_NAME: tienda-db
       run: |
+        # Validación crítica: si no hay registry, abortar
+        if [ -z "$ECR_REGISTRY" ]; then
+          echo "Error: ECR_REGISTRY esta vacio. Verifica permisos de AWS."
+          exit 1
+        fi
+        
         cd db
         docker build -t $IMAGE_NAME .
         docker tag $IMAGE_NAME:latest "$ECR_REGISTRY/$IMAGE_NAME:latest"
